"""Alert definitions and data structures."""

import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional
from src.evaluator.engine import DetectionResult


@dataclass
class Alert:
    """Represents a standardized detection alert generated by the engine."""
    alert_id: str
    rule_id: str
    title: str
    description: str
    severity: str
    confidence: float
    host_id: str
    timestamp: str
    event_id: Optional[str]
    evidence: Dict[str, Any]
    mitre_tactic: Optional[str] = None
    mitre_technique: Optional[str] = None
    tags: List[str] = field(default_factory=list)

    @classmethod
    def from_detection_result(cls, result: DetectionResult) -> "Alert":
        rule = result.rule
        event = result.event
        
        mitre_tactic = rule.mitre.tactic if rule.mitre else None
        mitre_technique = rule.mitre.technique if rule.mitre else None

        return cls(
            alert_id=f"ALT-{uuid.uuid4().hex[:8].upper()}",
            rule_id=rule.id,
            title=rule.name,
            description=rule.description,
            severity=rule.severity.value if hasattr(rule.severity, "value") else str(rule.severity),
            confidence=rule.confidence,
            host_id=event.get("host_id", "UNKNOWN_HOST"),
            timestamp=event.get("timestamp", datetime.utcnow().isoformat() + "Z"),
            event_id=event.get("event_id"),
            evidence=result.matched_evidence,
            mitre_tactic=mitre_tactic,
            mitre_technique=mitre_technique,
            tags=rule.tags,
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
